### ISSUE TITLE
Esoteric Skills are not working

### ISSUE THREAD

**Issue by schrottsimon** [any-other-guy/LostArk-Endless-Chaos#16]
Wardancer and Striker Spender skills are not being used.

**Comment by any-other-guy** [comment]
the caveat for now is that class identity is not supported, because some are very different than others.
and also 'hold' spells are poorly supported, avoid them for now.
I would recommend instant spell and cast spell, especially with large AoE on its own or have certain tripod to do so.

**Comment by any-other-guy** [comment]
also don't forget to go through settings in config.py, to let the bot know what kind of spells are sitting on your slot.
