### ISSUE TITLE
Accidently entered Stage3 of Chaos, then stuck

### ISSUE THREAD

**Issue by 85256638** [any-other-guy/LostArk-Endless-Chaos#26]
![Capture](https://user-images.githubusercontent.com/3270742/208324811-fa393a24-0303-4a9b-95f8-aa23f1c37bd8.PNG)

**Comment by 85256638** [comment]
error still happening

**Comment by any-other-guy** [comment]
fixed, please re-pull the project. Or just create a new folder called 'debug' in the project root directory.
Thanks for pointing out the issue!
