### ISSUE TITLE
Support of machinist and berserker transform

### ISSUE THREAD

**Issue by Ethan-XUD** [any-other-guy/LostArk-Endless-Chaos#36]
Is there a way to support transform classes like machinist and berserker?
我把Z键的cast time改成这样可以吗？
        {
            "key": "z",
            "abilityType": "specialty1",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 20000,
            "position": {"left": 895, "top": 839, "width": 13, "height": 12},
            "directional": False,
        },
比如Machinist变身是20秒，cast 20秒会不会让其他技能不能按呢？

**Comment by Ethan-XUD** [comment]
I have tried another way. Will submit merge request if that code works.

**Comment by ShayneAustinHanson95** [comment]
Issue https://github.com/any-other-guy/LostArk-Endless-Chaos/issues/63 has a solution to the mayhem part of this.
Machinist would be a tad more complicated, as it has to keep re-entering once guage is filled, where mayhem just goes in at the start and re-enters if it dies.
