### ISSUE TITLE
Are all classes supported?, can it run on North Vern ?

### ISSUE THREAD

**Issue by abdelrahman-essawy** [any-other-guy/LostArk-Endless-Chaos#40]
Hello guys,
thank you for the great bot!

however, I would like to ask are glaivier class supported?
In config I only see 4 classes.

also, when I start the bot it automatically goes to south vern, is it possible to make it go for north vern ?

thank you.

**Comment by ShayneAustinHanson95** [comment]
All classes are supported, if your class isn't in abilities yet you will have to add it

**Comment by any-other-guy** [comment]
you will have to set your own spells for different classes, and try to optimize them by setting the correct spell duration and etc.
