### ISSUE TITLE
bot doesnt switch to others characters

### ISSUE THREAD

**Issue by MatrixMonster123** [any-other-guy/LostArk-Endless-Chaos#46]
hello, i would like to ask on how to get the bot to switch to other characters after finishing two runs in the khaos dungeon and also doing lopang, i have it enabled with of couirse having multi character set to true as well but nothing, pls if anyone can help i would very much appreciate it

**Comment by any-other-guy** [comment]
please make sure you set your characters.py, and also set your 'mainCharacter' in config.py
