### ISSUE TITLE
Bot spamming same spell

### ISSUE THREAD

**Issue by zoredz** [any-other-guy/LostArk-Endless-Chaos#52]
![cmd](https://user-images.githubusercontent.com/129632234/229326409-d695cac5-aae1-4353-bad9-66e10afac4dc.png)
Hello thank you for ur job / i have a little problem with a bot 
Chaos start and bot do it was no't the problem 
the problem is bot spamming one spell always 
On Cmd he say ""unable to do a spell for 15s check if disconnect 
after these 15s he do other spell and continue to do this chaos 
someone know how i can fix this one 

have nice day

**Comment by Its-arab** [comment]
I'm also having the same issue, Boot continues to spam the same spell

**Comment by any-other-guy** [comment]
@Its-arab @zoredz please set "GFN" field to be True in config.py for now. There is some old deprecated code/settings that I haven't got a chance to clean them up.
